feat: Improve InlineFuncs size heuristic (#1771)
Improves the `MaxSize` heuristic for function inlining by checking
transitive caller's sizes.
That prevents us from exponential size grow when multiple small
functions call each other.

The check counts an estimate size for the descendants if they were to be
inlined, and adds it to the size of the caller function. This prevents a
panic in the `tests.integration.std.test_random-test_pcg32_compile.hugr`
where we ended up generating too many calls to a function declaration,
due to the callers being copied lots of times.

```
pyo3_runtime.PanicException: Outgoing port count exceeds maximum.
portgraph-0.16.1/src/portgraph.rs:548:9
```

Bumps the default MaxSize from 64 to 128 to account for these added
counts.