ci: remove --no-project flag to uv (#1775)
It's not clear the --no-project flag is doing anything - this is from a
CI run:
```
Run uv run --no-project which pytest
warning: `--frozen` has no effect when used alongside `--no-project`
/home/runner/work/tket2/tket2/.venv/bin/pytest
```

but on my local machine, `--no-project` avoids using the .venv and
instead looks for a system-installed pytest, thus `uv run --no-project
pytest` typically fails with:
```
error: Failed to spawn: `pytest`
  Caused by: No such file or directory (os error 2)
```

Thus, if there's any reason that we need the `--no-project`, then at the
least we should understand why it behaves differently in CI, and
comment.

But this PR takes the viewpoint that there is no need for
`--no-project`, hence removing it to avoid confusion.